epochs: 24
batch_size: 4
n_cpu: 0 #4
n_gpu: '0'
#data_root_dir: '/home/featurize/data/VOCdevkit2012/VOC2012'
data_root_dir: 'C:\datasets\VOCdevkit\VOC2007'
#data_root_dir: 'D:\datasets\KITTI_VOC2007'
